services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - ${WORDPRESS_PORT}:80
    volumes:
      - wordpress:/var/www/html
      - wp_content:/var/www/html/wp-content
    environment:
      WP_CLI_PHP_ARGS: "-d auto_prepend_file=/var/www/html/wp-cli-bootstrap.php"
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    

  db:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wpcli:
      image: wordpress:cli
      depends_on:
        - db
        - wordpress
      volumes:
        - wordpress:/var/www/html
        - wp_content:/var/www/html/wp-content
        # - ./wp-config.php:/var/www/html/wp-config.php
      environment:
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
        WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_URL: ${WP_URL}
      entrypoint: wp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
      PMA_USER: ${WORDPRESS_DB_USER}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}


volumes:
  wordpress:
  wp_content:
  db:
